name: Publish and Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout master branch
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cruellays/http-cache:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - 
        name: Deploy to Azure Webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: http-cache
          publish-profile: ${{ secrets.HTTPCACHE_PUBLISH_PROFILE }}
          images: cruellays/http-cache:latest
